/// BATADV netlink attributes (from linux/uapi/batman_adv.h)
#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Attribute {
    BatadvAttrUnspec = 0,
    BatadvAttrVersion = 1,
    BatadvAttrAlgoName = 2,
    BatadvAttrMeshIfindex = 3,
    BatadvAttrMeshIfname = 4,
    BatadvAttrMeshAddress = 5,
    BatadvAttrHardIfindex = 6,
    BatadvAttrHardIfname = 7,
    BatadvAttrHardAddress = 8,
    BatadvAttrOrigAddress = 9,
    BatadvAttrTpMeterResult = 10,
    BatadvAttrTpMeterTestTime = 11,
    BatadvAttrTpMeterBytes = 12,
    BatadvAttrTpMeterCookie = 13,
    BatadvAttrPad = 14,
    BatadvAttrActive = 15,
    BatadvAttrTtAddress = 16,
    BatadvAttrTtTtvn = 17,
    BatadvAttrTtLastTtvn = 18,
    BatadvAttrTtCrc32 = 19,
    BatadvAttrTtVid = 20,
    BatadvAttrTtFlags = 21,
    BatadvAttrFlagBest = 22,
    BatadvAttrLastSeenMsecs = 23,
    BatadvAttrNeighAddress = 24,
    BatadvAttrTq = 25,
    BatadvAttrThroughput = 26,
    BatadvAttrBandwidthUp = 27,
    BatadvAttrBandwidthDown = 28,
    BatadvAttrRouter = 29,
    BatadvAttrBlaOwn = 30,
    BatadvAttrBlaAddress = 31,
    BatadvAttrBlaVid = 32,
    BatadvAttrBlaBackbone = 33,
    BatadvAttrBlaCrc = 34,
    BatadvAttrDatCacheIp4Address = 35,
    BatadvAttrDatCacheHwAddress = 36,
    BatadvAttrDatCacheVid = 37,
    BatadvAttrMcastFlags = 38,
    BatadvAttrMcastFlagsPriv = 39,
    BatadvAttrVlanId = 40,
    BatadvAttrAggregatedOgmsEnabled = 41,
    BatadvAttrApIsolationEnabled = 42,
    BatadvAttrIsolationMark = 43,
    BatadvAttrIsolationMask = 44,
    BatadvAttrBondingEnabled = 45,
    BatadvAttrBridgeLoopAvoidanceEnabled = 46,
    BatadvAttrDistributedArpTableEnabled = 47,
    BatadvAttrFragmentationEnabled = 48,
    BatadvAttrGwBandwidthDown = 49,
    BatadvAttrGwBandwidthUp = 50,
    BatadvAttrGwMode = 51,
    BatadvAttrGwSelClass = 52,
    BatadvAttrHopPenalty = 53,
    BatadvAttrLogLevel = 54,
    BatadvAttrMulticastForceFloodEnabled = 55,
    BatadvAttrNetworkCodingEnabled = 56,
    BatadvAttrOrigInterval = 57,
    BatadvAttrElpInterval = 58,
    BatadvAttrThroughputOverride = 59,
    BatadvAttrMulticastFanout = 60,
}

impl From<Attribute> for u16 {
    fn from(a: Attribute) -> Self {
        a as u16
    }
}
